name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # bad-commit-check:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   name: Bad Commit Check

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Get changed files
  #       id: changed_files
  #       uses: tj-actions/changed-files@v46.0.1
  #       with:
  #         files: |
  #           **/node_modules/**
  #           **/.env
  #           **/*.env.*
  #           **/venv/**
  #           **/.venv/**

  #     - name: Fail if bad files added
  #       if: steps.changed_files.outputs.any_changed == 'true' || steps.changed_files.outputs.any_modified == 'true'
  #       run: |
  #         echo "Error: you fucked up"
  #         exit 1

  # for frontend
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Build (frontend)
    # needs: bad-commit-check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: ESLint (frontend)
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: ESLint
        run: npm run lint
        working-directory: ./frontend

  typecheck:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Typecheck (frontend)
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Typecheck
        run: npm run typecheck
        working-directory: ./frontend

  prettier:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Prettier (frontend)
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Prettier
        run: npm run prettier-check
        working-directory: ./frontend
